### PR TITLE
Bugfix: fail on critical build errors

### LINKED ISSUE #15: No critical error in workflow when teachbooks is not found
This issue is a follow-up on [this](https://github.com/TeachBooks/learn-python/issues/5#issuecomment-2080390337) comment from @Tom-van-Woudenberg in [Learn-Python Issue 5](https://github.com/TeachBooks/learn-python/issues/5).

_I think_ that no critical error happened in the workflow because of [this](https://github.com/TeachBooks/deploy-book-workflow/pull/11/files) change. 

Before this change, it would raise the error `teachbooks: command not found` , after this change it wouldn't happen anymore.. probably because both `stdout` and `stderr` are being redirected to `tee`? In any case, it's better if @severinbratus takes a look into it. :D

### PR DESCRIPTION
**Pull request by severinbratus**
(not yet tested)

Resolves #15, #18

### CODE REVIEW

**Review by Tom-van-Woudenberg — CHANGES_REQUESTED** [review]
@severinbratus , thanks again!

I've tested it here: https://github.com/TeachBooks/testable-template/actions/runs/8880318945

Could you still provide a summary which includes the branches which are published anyway?
And would it be possible to add the traceback (in case of a jupyter book build issue, for example the issue starting here https://github.com/TeachBooks/testable-template/actions/runs/8880318945/job/24380098298#step:7:38) or the previous line in case of another error (https://github.com/TeachBooks/testable-template/actions/runs/8880318945/job/24380099268#step:7:36 this line, but not sure whether it's always just one line)
And would it be possible to show the summary at the top? So above annotations, artifacts and non-critical errors summaries? That's still the most important one so it would be a bity if that's hidden somewhere

**Comment by Tom-van-Woudenberg** [comment]
> @severinbratus , thanks again!
> 
> I've tested it here: https://github.com/TeachBooks/testable-template/actions/runs/8880318945
> 
> Could you still provide a summary which includes the branches which are published anyway? And would it be possible to add the traceback (in case of a jupyter book build issue, for example the issue starting here https://github.com/TeachBooks/testable-template/actions/runs/8880318945/job/24380098298#step:7:38) or the previous line in case of another error (https://github.com/TeachBooks/testable-template/actions/runs/8880318945/job/24380099268#step:7:36 this line, but not sure whether it's always just one line) And would it be possible to show the summary at the top? So above annotations, artifacts and non-critical errors summaries? That's still the most important one so it would be a bity if that's hidden somewhere

To note, here's another type of error which is properly shown: https://github.com/TeachBooks/testable-template/actions/runs/8880522755

**Comment by severinbratus** [comment]
> And would it be possible to show the summary at the top? So above annotations, artifacts and non-critical errors summaries? That's still the most important one so it would be a bity if that's hidden somewhere

Yes, I now see a way to do this: upload a summary artifact from each branch-building job, and then download & combine them later.

> Could you still provide a summary which includes the branches which are published anyway?

Yes, this should be compatible with the approach above.

> And would it be possible to add the traceback (in case of a jupyter book build issue, for example the issue starting here https://github.com/TeachBooks/testable-template/actions/runs/8880318945/job/24380098298#step:7:38) or the previous line in case of another error (https://github.com/TeachBooks/testable-template/actions/runs/8880318945/job/24380099268#step:7:36 this line, but not sure whether it's always just one line)

By *add traceback*, do you mean to have more descriptive error messages than `Error: Process completed with exit code 127`? I do not think this is possible -- this is how it has been before as well https://github.com/TeachBooks/testable-template/actions/runs/8838899318

**Comment by Tom-van-Woudenberg** [comment]
> > And would it be possible to add the traceback (in case of a jupyter book build issue, for example the issue starting here https://github.com/TeachBooks/testable-template/actions/runs/8880318945/job/24380098298#step:7:38) or the previous line in case of another error (https://github.com/TeachBooks/testable-template/actions/runs/8880318945/job/24380099268#step:7:36 this line, but not sure whether it's always just one line)
> 
> By _add traceback_, do you mean to have more descriptive error messages than `Error: Process completed with exit code 127`? I do not think this is possible -- this is how it has been before as well https://github.com/TeachBooks/testable-template/actions/runs/8838899318

Yes, to have the lines above the exit code error echoed as well. So in case of the first link, the lines 107 - 110 and in case of the second link, the line 35. The exit code is not descriptive, while the description is there in those lines above. If it's not possible maybe provide instructions how to find those?

**Comment by severinbratus** [comment]
@Tom-van-Woudenberg Please see https://github.com/TeachBooks/testable-template/actions/runs/8951772242 for an example that includes all three:
1. non-critical error (NOTE: this will disappear from the summary on the second run due to caching)
2. critical build error
3. teachbooks missing

**Review by Tom-van-Woudenberg — CHANGES_REQUESTED** [review]
Now tested also the `error` errors instead of only `warning`: https://github.com/TeachBooks/testable-template/actions/runs/8952818422. Works very nice!

One additional change: Could you add to the branches-depoloyed table for all branches which contained a critical error that the branch is not deployed (+ influence on primary branch and aliases)

**Comment by severinbratus** [comment]
Resolves #23 now as well, see https://github.com/TeachBooks/testable-template/actions/runs/8967130932 I plan to make a new Issue & PR for the change request on marking failed branches in the table

**Review by Tom-van-Woudenberg — APPROVED** [review]

**Pull request merged**
